services:
  backend:
    build: ./backend
    container_name: api-health-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: api-health-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend